version: '3'

services:
  db:
    container_name: postgres
    image: 'postgres:9.5'
    volumes:
      - './postgres-data:/var/lib/postgresql'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=hello_flask
      - POSTGRES_PASSWORD=hello_flask
      - POSTGRES_DB=hello_flask_dev
  website:
    container_name: website
    build: .
    env_file:
      - '.env'
    volumes:
      - '.:/app'
    ports:
      - '8000:8080'
    depends_on:
      - db

volumes:
  enferno:
  redis:
  db:
networks:
  default:
    # Use a custom driver
    driver: custom-driver-1